import Header from './components/header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './redux/provider'
import 'react-loading-skeleton/dist/skeleton.css'
import Skeleton, { SkeletonTheme } from 'react-loading-skeleton';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Social',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-white'>
      <body
        // className={inter.className}
        className='bg-white'
      >
        <Providers>
          <SkeletonTheme baseColor="#b8b5b5" highlightColor="#444">
            <Header />
            {children}
          </SkeletonTheme>
        </Providers>
      </body>
    </html>
  )
}
