export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_ERROR = "CREATE_POST_ERROR"

export const ALL_POST_REQUEST = "ALL_POST_REQUEST"
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS"
export const ALL_POST_ERROR = "ALL_POST_ERROR"

export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"


